title: Project Based Learning
description: Project based learning portal with programming tutorials, coding project ideas, and curated resources by language.
url: https://dvurechensky-docs.github.io
baseurl: /ProjectBasedLearning
lang: en
plugins:
  - jemoji
  - jekyll-mentions
collections:
  categories:
    output: true
